import "./globals.css";
import Navbar from "@/components/Navbar";
import { UserProvider } from "@/context/UserContext";

export const metadata = {
  title: "Trip Logic - Your Trip Our Logic",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en">
      <body className="bg-gray-200 bg-[url('/images/explore-kota-background-image-1.png')]">
        <UserProvider>
          <Navbar />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
